apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: fraud-detection
    newName: fraud-detection
    newTag: dev

patches:
  - path: image-pull-policy.yaml
