global:
  environment: dev

worker:
  replicaCount: 1
  image:
    repository: fraud-detection
    tag: dev
    pullPolicy: Never

api:
  replicaCount: 1
  image:
    repository: fraud-detection
    tag: dev
    pullPolicy: Never

kong:
  service:
    type: NodePort
    port: 80
    targetPort: 8000
    nodePort: null
  ingress:
    enabled: false
