global:
  environment: prod
worker:
  replicaCount: 2
  image:
    repository: ghcr.io/siyablela/fraud_detection
    tag: 03f2e846c6a3256ae6f78073b9f23f51d126e40c
    pullPolicy: IfNotPresent
api:
  replicaCount: 2
  image:
    repository: ghcr.io/siyablela/fraud_detection
    tag: 03f2e846c6a3256ae6f78073b9f23f51d126e40c
    pullPolicy: IfNotPresent
security:
  jwtIssuer: https://auth.example.com/
  jwtAudience: fraud-api
  jwtJwksUrl: https://auth.example.com/.well-known/jwks.json
  jwtPublicKeyPath: ''
  requiredReadScope: fraud:transactions:read
  requiredWriteScope: fraud:transactions:write
kafkaSecurity:
  protocol: SSL
  truststorePath: /etc/kafka/tls/kafka-ca.pem
  keystoreCertPath: /etc/kafka/tls/kafka-client.crt
  keystoreKeyPath: /etc/kafka/tls/kafka-client.key
producer:
  replicaCount: 2
  image:
    repository: ghcr.io/siyablela/fraud_detection
    tag: 03f2e846c6a3256ae6f78073b9f23f51d126e40c
    pullPolicy: IfNotPresent
resilience:
  enablePreferredAntiAffinity: true
  topologyKey: kubernetes.io/hostname
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  autoscaling:
    enabled: true
    api:
      minReplicas: 2
      maxReplicas: 8
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    producer:
      minReplicas: 2
      maxReplicas: 8
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    worker:
      minReplicas: 2
      maxReplicas: 8
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    kong:
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
certManager:
  enabled: true
  issuerKind: ClusterIssuer
  issuerName: letsencrypt-prod
  ingressHost: fraud-api.example.com
  secretName: fraud-api-tls
kong:
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1m
      nginx.ingress.kubernetes.io/proxy-read-timeout: '30'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '30'
    hosts:
    - host: fraud-api.example.com
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - fraud-api.example.com
      secretName: fraud-api-tls
