global:
  environment: production

# Application Secrets (Change these in production)
secrets:
  postgresPassword: "change-me"

# Custom Internal Applications (Built from your local context)
worker:
  replicaCount: 1
  image:
    repository: fraud-worker
    tag: latest
    pullPolicy: IfNotPresent

api:
  replicaCount: 1
  image:
    repository: fraud-api
    tag: latest
    pullPolicy: IfNotPresent

producer:
  replicaCount: 1
  image:
    repository: fraud-producer
    tag: latest
    pullPolicy: IfNotPresent

appConfig:
  kafkaTopicName: transactions_topic
  kafkaConsumerGroupId: fraud-worker-group
  dbPoolMinSize: 1
  dbPoolMaxSize: 10
  defaultHighValueThreshold: 10000
  defaultRestrictedCategoriesJson: '{"GAMBLING": 5000, "CRYPTO": 5000}'

observability:
  logLevel: INFO
  enableTracing: false
  workerMetricsPort: 9100
  otlpEndpoint: ""

instana:
  enabled: false
  otlpEndpoint: "http://instana-agent.instana-agent.svc.cluster.local:4318/v1/traces"

# Infrastructure Components (Third-Party Images)
postgres:
  image: postgres:16-alpine
kafka:
  image: apache/kafka:latest
keycloak:
  image: quay.io/keycloak/keycloak:26.0
kong:
  image: kong:3.8
kafkaUi:
  image: ghcr.io/kafbat/kafka-ui:latest

# Application Configurations (Injected via ConfigMap)
rulesConfig: |
  {
    "example_rule": "fraud_rules_go_here"
  }

kongConfig: |
  _format_version: "3.0"
  services: []

