global:
  environment: prod
worker:
  replicaCount: 2
  image:
    repository: ghcr.io/siyablela/fraud_detection
    tag: 3f26683fb61bb96ba6173f00290376aac31ac1ec
    pullPolicy: Always
api:
  replicaCount: 2
  image:
    repository: ghcr.io/siyablela/fraud_detection
    tag: 3f26683fb61bb96ba6173f00290376aac31ac1ec
    pullPolicy: Always
security:
  jwtIssuer: https://auth.example.com/
  jwtAudience: fraud-api
  jwtJwksUrl: https://auth.example.com/.well-known/jwks.json
  jwtPublicKeyPath: ''
  jwtAlgorithms: RS256
  requiredReadScope: fraud:transactions:read
  authTokenEndpointEnabled: false
  keycloakAdminUrl: http://keycloak:8081
  keycloakAdminUsername: '{{ vault:secret/data/keycloak/admin#username }}'
  keycloakAdminPassword: '{{ vault:secret/data/keycloak/admin#password }}'
  keycloakDemoUsername: '{{ vault:secret/data/keycloak/demo#username }}'
  keycloakDemoPassword: '{{ vault:secret/data/keycloak/demo#password }}'
  keycloakTokenClientId: fraud-cli
  keycloakTokenClientSecret: '{{ vault:secret/data/keycloak/clients#token-client-secret
    }}'
  keycloakServiceClientId: fraud-service-cli
  keycloakServiceClientSecret: '{{ vault:secret/data/keycloak/clients#service-client-secret
    }}'
  keycloakServiceTokenScope: '{{ vault:secret/data/keycloak/clients#service-token-scope
    }}'
kafkaSecurity:
  protocol: PLAINTEXT
resilience:
  enablePreferredAntiAffinity: true
  topologyKey: kubernetes.io/hostname
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  autoscaling:
    enabled: true
    api:
      minReplicas: 2
      maxReplicas: 8
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    worker:
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    kong:
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
certManager:
  enabled: true
  issuerKind: ClusterIssuer
  issuerName: letsencrypt-prod
  ingressHost: fraud-api.example.com
  secretName: fraud-api-tls
kong:
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1m
      nginx.ingress.kubernetes.io/proxy-read-timeout: '30'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '30'
    hosts:
    - host: fraud-api.example.com
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - fraud-api.example.com
      secretName: fraud-api-tls
