apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-configs
data:
  # The "|" tells YAML to treat the following indented text as a literal multi-line string
  rules.json: |
{{ .Values.rulesConfig | indent 4 }}
  kong.yml.tpl: |
{{ .Values.kongConfig | indent 4 }}
