apiVersion: v1
kind: Secret
metadata:
  name: fraud-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-configs
data:
  # The "|" tells YAML to treat the following indented text as a literal multi-line string
  rules.json: |
{{ .Values.rulesConfig | indent 4 }}
  kong.yml: |
{{ .Values.kongConfig | indent 4 }}
