{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecretName }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-configs
data:
  # The "|" tells YAML to treat the following indented text as a literal multi-line string
  rules.json: |
{{ .Values.rulesConfig | indent 4 }}
  kong.yml: |
{{ .Values.kongConfig | indent 4 }}
