# --- KONG ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: {{ .Values.kong.image }}
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/kong.yml
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
          volumeMounts:
            - name: kong-volume
              mountPath: /kong/kong.yml
              subPath: kong.yml
      volumes:
        - name: kong-volume
          configMap:
            name: fraud-configs
---
apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  type: NodePort # Allows local or load balancer mapping access
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
    - name: admin
      port: 8001
  selector:
    app: kong

# --- KEYCLOAK ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          args: ["start-dev"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: keycloak

# --- KAFKA UI ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUi.image }}
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: KAFKA_CLUSTERS_0_NAME
              value: "Local-Fraud-Cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS:
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  ports:
    - port: 8080
  selector:
    app: kafka-ui
