apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init-topic
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-init
          image: {{ .Values.kafka.image }}
          command: ["/opt/kafka/bin/kafka-topics.sh"]   # <--- FIX: This is entrypoint in K8s
          args:                                          # <--- FIX: This is command in K8s
            - "--create"
            - "--if-not-exists"
            - "--bootstrap-server"
            - "kafka:9092"
            - "--partitions"
            - "3"
            - "--replication-factor"
            - "1"
            - "--topic"
            - "transactions_topic"

