apiVersion: v1
kind: Service
metadata:
  name: fraud-api
  labels:
    app.kubernetes.io/name: fraud-api
    app.kubernetes.io/part-of: fraud-detection
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fraud-api
  ports:
    - name: http
      port: 8000
      targetPort: http
